name: Golang Formatter
on: [pull_request]
jobs:
  build:
    name: Golang Formatter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
        
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges.
        go-version: 1.15.6
      
    - name: Golang Formatter
      uses: inohmonton99/auto-go-format@master
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
