name: Go

on:
  push:
    branches: '*'  
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
      
    - name: Format
      run: go fmt ./...
      working-directory: .
      
    - name: cwd
      run: ls -altrh
